const FETCH_USERS_LIST = 'FETCH_USERS_LIST';
const FETCH_USERS_LIST_SUCCESS = 'FETCH_USERS_LIST_SUCCESS';
const FETCH_USERS_LIST_FAILURE = 'FETCH_USERS_LIST_FAILURE';
const FETCH_CAMPAIGN_LIST = 'FETCH_CAMPAIGN_LIST';
const LOADING_INDICATOR = 'LOADING_INDICATOR';
const SET_NAME = 'SET_NAME';
const SET_STARTDATE = 'SET_STARTDATE';
const SET_ENDDATE = 'SET_ENDDATE';
const SET_FILTERED_DATA = 'SET_FILTERED_DATA';
const FETCH_CAMPAIGN_LIST_FAILURE = "FETCH_CAMPAIGN_LIST_FAILURE";

export {
  FETCH_USERS_LIST,
  FETCH_USERS_LIST_SUCCESS,
  FETCH_USERS_LIST_FAILURE,
  FETCH_CAMPAIGN_LIST,
  FETCH_CAMPAIGN_LIST_FAILURE,
  LOADING_INDICATOR,
  SET_NAME,
  SET_STARTDATE,
  SET_ENDDATE,
  SET_FILTERED_DATA
};
